### PR TITLE
3 game page frontend

### LINKED ISSUE #3: game page frontend

### PR DESCRIPTION
**Pull request by TinaGu0**

### CODE REVIEW

**Comment by whydoesthecodenotwork** [comment]
Photogtaphy

**Comment by wwormseason** [comment]
???

**Comment by whydoesthecodenotwork** [comment]
https://github.com/sitechtimes/ai-vs-human-art-frontend/blob/c55f08a93f1a364af6887e00b646dbac89ee704c/frontend/src/views/GameView.vue#L64

**Comment by wwormseason** [comment]
its fixed lawrence u cna rejoice

**Comment by wwormseason** [comment]
can*

**Pull request merged**
