### PR TITLE
signwhateverthebuttonsequencefromremotecontrolispage.vue

### PR DESCRIPTION
**Pull request by whydoesthecodenotwork**
image
image

the method of choosing sign up/in is a joke, but it does work. sign out works too
though there's an actual change that you should really implement:
- login and register now have properly typed parameters. username, password, and email shouldn't be null

### CODE REVIEW

**Comment by wwormseason** [comment]
Lawrence i love u but i think ill just take angelinas suggestion to make it a link, i will def change the userstore type parameters tho

**Comment by whydoesthecodenotwork** [comment]
"this [referring to your toggle button] is horrible. green is a horrible color. dropdown is way more rational. it's more intuitive. people should catch on the trends"
\- jay chen 2024 (reliable source - got a 1 on the apcsp exam)

**Comment by wwormseason** [comment]
1) the green color will be changed as u can see from the themes issue
2) its not a trend yet you just came up with it

**Comment by whydoesthecodenotwork** [comment]
every trend has its trendsetters and it just so happens that i am the first
#StopTheHate #ThrowYifanAtTheEarth

**Pull request closed without merging**
