### PR TITLE
i fixed it, im so fucking great (i ran one command) (lawrence i hope…

### LINKED ISSUE #13: vulnerabilities
image
please fix IMMEDIATELY my family is STARVING because of this

### PR DESCRIPTION
**Pull request by wwormseason**
… ur family STARVES)

### CODE REVIEW

**Comment by whydoesthecodenotwork** [comment]
image

**Comment by whydoesthecodenotwork** [comment]
onme command

**Comment by wwormseason** [comment]
Im going to blow you up

**Comment by whydoesthecodenotwork** [comment]
image

**Pull request merged**
